// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/19 下午11:34:52
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/project/tw-dehumidifier-guide/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/tw-dehumidifier-guide/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/tw-dehumidifier-guide/plugins/**/*.{js,ts,mjs}","D:/project/tw-dehumidifier-guide/composables/**/*.{js,ts,mjs}","D:/project/tw-dehumidifier-guide/utils/**/*.{js,ts,mjs}","D:/project/tw-dehumidifier-guide/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/tw-dehumidifier-guide/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/project/tw-dehumidifier-guide/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/project/tw-dehumidifier-guide/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;