// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/19 下午12:11:20
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/project/test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/test/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/test/plugins/**/*.{js,ts,mjs}","D:/project/test/composables/**/*.{js,ts,mjs}","D:/project/test/utils/**/*.{js,ts,mjs}","D:/project/test/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/project/test/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/project/test/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/project/test/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;